Feature/net6 upgrade
jobbrIO/jobbr-dashboard pull request #36
Opened 2022-12-28 10:31 UTC by mara-huminiuc

2022-12-28 11:08 UTC, eXpl0it3r requested changes
Mostly some changes in the tests area.

Can you explain how the new dashboard frontend loading works exactly?

2022-12-28 12:46 UTC, mara-huminiuc commented on source/Jobbr.Dashboard/DashboardBackend.cs
> +                Task.Run(async () => await _webApp.DisposeAsync());
WebApplication doesn't have a syncronous Dispose method

2022-12-28 12:57 UTC, mara-huminiuc commented on source/Jobbr.Dashboard.Frontend/jobbr-dashboard/package-lock.json
> -        },
No idea why this was removed. Maybe @RKivioja would know? Otherwise I can revert.

2022-12-28 12:59 UTC, RKivioja commented on source/Jobbr.Dashboard.Frontend/jobbr-dashboard/package-lock.json
> -        },
I am pretty sure building the frontend caused this. I did not manually remove any packages.

2022-12-28 13:08 UTC, mara-huminiuc commented on source/Jobbr.Dashboard.Frontend/jobbr-dashboard/package-lock.json
> -        },
I assumed so myself, I reverted and tried to reproduce but it wasn't removed the 2nd time, so I am putting it back

2022-12-28 13:49 UTC, mara-huminiuc commented on source/Jobbr.Dashboard/DashboardBackend.cs
> +            _webApp.UseFileServer(new FileServerOptions
Yes, the zip file is going to be read if it's added as an embedded resource

2022-12-28 14:10 UTC, eXpl0it3r requested changes
Two small things

2022-12-28 14:10 UTC, eXpl0it3r commented on source/Jobbr.Dashboard.Tests/DashboardBackendTests.cs
> +
Remove empty space

2022-12-28 14:10 UTC, eXpl0it3r commented on source/Jobbr.Dashboard.Tests/DashboardBackendTests.cs
> +            _loggerFactory = new NullLoggerFactory();
I'd probably just inline it.

2022-12-28 14:11 UTC, eXpl0it3r commented on source/Jobbr.Dashboard/DashboardBackend.cs
> +            var builder = WebApplication.CreateBuilder();
Or what about using the web host as we did for the WebAPI?

2023-01-03 08:30 UTC, eXpl0it3r approved these changes
Great work! 🥳

2023-01-03 08:33 UTC, merged